ESTUDIANTE: LUIS FERNANDO PAIZ VIRULA
TAREA 5

CARGA DE SET DE DATOS DESDE LOS .CSV
```{r}
library(tidyverse)
questions <- read_csv('questions.csv')
answers <- read_csv('answers.csv')
tags <- read_csv('tags.csv')
question_tags <- read_csv('question_tags.csv')
```

1. LEFT-JOINING QUESTIONS AND TAGS
```{r}
questions_with_tags <- questions %>% #1.4
  left_join(question_tags, by=c("id" = "question_id")) %>% #1.1
  left_join(tags, by=c("tag_id" = "id")) %>% #1.2
  replace_na(list(tag_name = "only-r")) #1.3 
```

2. COMPARING SCORES ACROSS TAGS
```{r}
questions_with_tags %>%
  group_by(tag_name) %>% #2.1
  summarize(mean_score = mean(score)) %>% #2.2
  arrange(desc(mean_score)) #2.3
```

3. FINDING GAPS BETWEEN QUESTIONS AND ANSWER
```{r}
questions
answers
questions %>%
  inner_join(answers, by = c("id" = "question_id"), suffix = c("_question", "_answer")) %>% #3.1
  mutate(gap = creation_date_answer - creation_date_question) #3.2

```

4. JOINING QUESTION AND ANSWER COUNTS
```{r}
answer_counts <- answers %>% #4.1
  group_by(question_id) %>% #4.1
  count(question_id) %>% #4.1
  arrange(question_id) #4.1
 
question_answer_counts <- questions %>% #4.4
  left_join(answer_counts, by = c("id" = "question_id")) %>% #4.2
  replace_na(list(n = 0)) #4.3
```

5. JOINING QUESTIONS, ANSWERS, AND TAGS
```{r}
question_tags %>%
  inner_join(question_answer_counts, by = c("question_id" = "id")) %>% #5.1
  inner_join(tags, by = c("tag_id" = "id")) %>% #5.2
  arrange(desc(n)) #Se identifica que el tema de mayor interés en R es statistics y r-faq en Stack Overflow :)
```

